'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FileBrowser
    
    '''<summary>
    '''tableMainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tableMainContent As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''folderList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents folderList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tableFolders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tableFolders As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''trHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trHeader As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''tdFolderHeader1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFolderHeader1 As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''Button_Parent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button_Parent As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''tdFolderHeader2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFolderHeader2 As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''Panel_FolderList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FolderList As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ListView_Folders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListView_Folders As Global.System.Web.UI.WebControls.ListView
    
    '''<summary>
    '''fileList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fileList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Table_Attr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table_Attr As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''Tr2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tr2 As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''tdFilesHeader1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFilesHeader1 As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''Label_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Name As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tdFilesHeader2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFilesHeader2 As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''Label_Size control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Size As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tdFilesHeader3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFilesHeader3 As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''Label_LastWriteTimeUtc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_LastWriteTimeUtc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Panel_FileList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FileList As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ListView_Files control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListView_Files As Global.System.Web.UI.WebControls.ListView
End Class
