'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MisOfertas
    
    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''TB_Nombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Nombre As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TB_Region control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Region As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TB_Precio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Precio As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Lbl_Pasajeros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_Pasajeros As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TB_Pasajeros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Pasajeros As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RE_TB_Pasajeros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RE_TB_Pasajeros As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''Lbl_Total control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_Total As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TB_Total control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Total As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_Continuar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Continuar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DIV_MdePago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DIV_MdePago As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Lbl_MdePago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_MdePago As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DDL_MdePago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_MdePago As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Lbl_NewSaldo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_NewSaldo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Panel_NC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_NC As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''DG_CC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DG_CC As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btn_Confirmar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Confirmar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Panel_SeleccionDeTarjeta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_SeleccionDeTarjeta As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Lbl_SelecTarjeta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_SelecTarjeta As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btn_Visa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Visa As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btn_Master control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Master As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btn_American control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_American As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''Panel_Tarjeta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Tarjeta As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''TB_NombreTitular control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_NombreTitular As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RE_TB_NombreTitular control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RE_TB_NombreTitular As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''Lbl_Tarjeta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_Tarjeta As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TB_NroTarjeta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_NroTarjeta As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RE_Visa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RE_Visa As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''RE_Master control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RE_Master As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''RE_American control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RE_American As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''TB_MesVencimiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_MesVencimiento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TB_AñoVencimiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_AñoVencimiento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TB_CodSeg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_CodSeg As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RE_TB_CodSeg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RE_TB_CodSeg As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''btn_EnviarPago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_EnviarPago As Global.System.Web.UI.WebControls.Button
End Class
