'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MisFacturas1
    
    '''<summary>
    '''Panel_NC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_NC As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''DG_Facturas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DG_Facturas As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''TB_Ingresar_Motivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Ingresar_Motivo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RFV_Cancelacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFV_Cancelacion As Global.System.Web.UI.WebControls.RequiredFieldValidator
End Class
