'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Reporte_Respuestas
    
    '''<summary>
    '''Div_ReporteTiempo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div_ReporteTiempo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbl_Preguntas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Preguntas As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbl_Respuestas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Respuestas As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbl_Porcentaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Porcentaje As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbl_TiempoPromedio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_TiempoPromedio As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
