'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Reportes_Encuestas
    
    '''<summary>
    '''Div_Encuestas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div_Encuestas As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Reporte_Encuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Reporte_Encuesta As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''btnVerEncuestas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVerEncuestas As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnVerFichaOpinion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVerFichaOpinion As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DG_Encuestas2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DG_Encuestas2 As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''Repeater1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Repeater1 As Global.System.Web.UI.WebControls.Repeater
End Class
