'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Servicios
    
    '''<summary>
    '''btn_Comparar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Comparar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hiddenItemCompare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenItemCompare As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btn_FinCompra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_FinCompra As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hiddenItemBuy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenItemBuy As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''RP_Ofertas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RP_Ofertas As Global.System.Web.UI.WebControls.Repeater
End Class
